#!/usr/bin/python

#heat map color palette generator

palette: list[int] = [0x1E1E2F, 0x303050, 0xA8CACA, 0xC0CA50, 0xFF8080]

inserted_color_count: int = 15


def color_lerp (color_a: int, color_b: int, t: float) -> int:
    red:   int = int((1 - t) * ((color_a >> 16) & 0xFF) + t * ((color_b >> 16) & 0xFF))
    green: int = int((1 - t) * ((color_a >>  8) & 0xFF) + t * ((color_b >>  8) & 0xFF))
    blue:  int = int((1 - t) * ((color_a >>  0) & 0xFF) + t * ((color_b >>  0) & 0xFF))
    
    return (red << 16) + (green << 8) + (blue << 0)


if __name__ == '__main__':
    i: int = 1
    
    while i < len(palette):
        color_a = palette[i - 1]
        color_b = palette[i]
        for j in range(inserted_color_count):
            palette.insert(i, color_lerp(color_a, color_b, (j + 1) / (inserted_color_count + 1)))
            i+=1
        i+=1
    
    output: str = "{\n"
    
    for color in palette:
        output += f"\t{hex(color)},\n"
        
    print(output[:-2] + "\n};")
